name: portefolio

services:
  frontend:
    container_name: portefolio
    image: ghcr.io/appolinairee/portefolio:latest
    ports:
      - "3003:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
